
keys = {"SMART VERT": [{"keymap": "Mesh", "idname": "machin3.smart_vert", "type": "ONE", "value": "PRESS", "properties": [("type", "LAST"), ("slide_override", False)]},
                       {"keymap": "Mesh", "idname": "machin3.smart_vert", "type": "ONE", "value": "PRESS", "shift": True, "properties": [("type", "CENTER"), ("slide_override", False)]},
                       {"keymap": "Mesh", "idname": "machin3.smart_vert", "type": "ONE", "value": "PRESS", "alt": True, "properties": [("type", "SMART"), ("slide_override", False)]},
                       {"keymap": "Mesh", "idname": "machin3.smart_vert", "type": "ONE", "value": "PRESS", "shift": True, "alt": True, "properties": [("slide_override", True)]}],
        "SMART EDGE": [{"keymap": "Mesh", "idname": "machin3.smart_edge", "type": "TWO", "value": "PRESS"}],
        "SMART FACE": [{"keymap": "Mesh", "idname": "machin3.smart_face", "type": "FOUR", "value": "PRESS"}],
        "CLEAN UP": [{"keymap": "Mesh", "idname": "machin3.clean_up", "type": "THREE", "value": "PRESS"}],
        "CLIPPING TOGGLE": [{"keymap": "3D View Generic", "space_type": "VIEW_3D", "idname": "machin3.clipping_toggle", "type": "BUTTON5MOUSE", "value": "PRESS"}],
        "FOCUS": [{"keymap": "Object Mode", "idname": "machin3.focus", "type": "F", "value": "PRESS", "ctrl": True}],
        "MIRROR": [{"keymap": "Object Mode", "idname": "machin3.mirror", "type": "X", "value": "PRESS", "alt": True, "shift": True, "properties": [("use_x", True), ("use_y", False), ("use_z", False)]},
                   {"keymap": "Object Mode", "idname": "machin3.mirror", "type": "Y", "value": "PRESS", "alt": True, "shift": True, "properties": [("use_x", False), ("use_y", True), ("use_z", False)]},
                   {"keymap": "Object Mode", "idname": "machin3.mirror", "type": "Z", "value": "PRESS", "alt": True, "shift": True, "properties": [("use_x", False), ("use_y", False), ("use_z", True)]}],
        "ALIGN": [{"keymap": "Object Mode", "idname": "machin3.align", "type": "A", "value": "PRESS", "alt": True}],

        "PIE MODES": [{"keymap": "Object Non-modal", "idname": "wm.call_menu_pie", "type": "TAB", "value": "PRESS", "properties": [("name", "VIEW3D_MT_MACHIN3_modes")]}],
        "PIE SAVE": [{"keymap": "Window", "idname": "wm.call_menu_pie", "type": "S", "value": "PRESS", "ctrl": True, "properties": [("name", "VIEW3D_MT_MACHIN3_save")]}],
        "PIE SHADING": [{"keymap": "3D View Generic", "space_type": "VIEW_3D", "idname": "wm.call_menu_pie", "type": "PAGE_UP", "value": "PRESS", "properties": [("name", "VIEW3D_MT_MACHIN3_shading")]}],
        "PIE VIEWS": [{"keymap": "3D View Generic", "space_type": "VIEW_3D", "idname": "wm.call_menu_pie", "type": "PAGE_DOWN", "value": "PRESS", "properties": [("name", "VIEW3D_MT_MACHIN3_views")]}],
        "PIE WORKSPACE": [{"keymap": "Window", "idname": "wm.call_menu_pie", "type": "PAUSE", "value": "PRESS", "properties": [("name", "VIEW3D_MT_MACHIN3_workspace")]}],
        }
