
keys = {"SMART_VERT": [{"label": "Merge Last", "keymap": "Mesh", "idname": "machin3.smart_vert", "type": "ONE", "value": "PRESS", "properties": [("type", "LAST"), ("slide_override", False)]},
                       {"label": "Merge Center", "keymap": "Mesh", "idname": "machin3.smart_vert", "type": "ONE", "value": "PRESS", "shift": True, "properties": [("type", "CENTER"), ("slide_override", False)]},
                       {"label": "Merge Smart", "keymap": "Mesh", "idname": "machin3.smart_vert", "type": "ONE", "value": "PRESS", "alt": True, "properties": [("type", "SMART"), ("slide_override", False)]},
                       {"label": "Slide Extend", "keymap": "Mesh", "idname": "machin3.smart_vert", "type": "ONE", "value": "PRESS", "shift": True, "alt": True, "properties": [("slide_override", True)]}],
        "SMART_EDGE": [{"keymap": "Mesh", "idname": "machin3.smart_edge", "type": "TWO", "value": "PRESS"}],
        "SMART_FACE": [{"keymap": "Mesh", "idname": "machin3.smart_face", "type": "FOUR", "value": "PRESS"}],
        "CLEAN_UP": [{"keymap": "Mesh", "idname": "machin3.clean_up", "type": "THREE", "value": "PRESS"}],
        "CLIPPING_TOGGLE": [{"keymap": "3D View Generic", "space_type": "VIEW_3D", "idname": "machin3.clipping_toggle", "type": "BUTTON5MOUSE", "value": "PRESS"}],
        "FOCUS": [{"keymap": "Object Mode", "idname": "machin3.focus", "type": "F", "value": "PRESS", "ctrl": True}],
        "MIRROR": [{"label": "X Axis", "keymap": "Object Mode", "idname": "machin3.mirror", "type": "X", "value": "PRESS", "alt": True, "shift": True, "properties": [("use_x", True), ("use_y", False), ("use_z", False)]},
                   {"label": "Y Axis", "keymap": "Object Mode", "idname": "machin3.mirror", "type": "Y", "value": "PRESS", "alt": True, "shift": True, "properties": [("use_x", False), ("use_y", True), ("use_z", False)]},
                   {"label": "Z Axis", "keymap": "Object Mode", "idname": "machin3.mirror", "type": "Z", "value": "PRESS", "alt": True, "shift": True, "properties": [("use_x", False), ("use_y", False), ("use_z", True)]}],
        "ALIGN": [{"keymap": "Object Mode", "idname": "machin3.align", "type": "A", "value": "PRESS", "alt": True}],

        "MODES_PIE": [{"keymap": "Object Non-modal", "idname": "wm.call_menu_pie", "type": "TAB", "value": "PRESS", "properties": [("name", "MACHIN3_MT_modes_pie")]}],
        "SAVE_PIE": [{"keymap": "Window", "idname": "wm.call_menu_pie", "type": "S", "value": "PRESS", "ctrl": True, "properties": [("name", "MACHIN3_MT_save_pie")]}],
        "SHADING_PIE": [{"keymap": "3D View Generic", "space_type": "VIEW_3D", "idname": "wm.call_menu_pie", "type": "PAGE_UP", "value": "PRESS", "properties": [("name", "MACHIN3_MT_shading_pie")]}],
        "VIEWS_PIE": [{"keymap": "3D View Generic", "space_type": "VIEW_3D", "idname": "wm.call_menu_pie", "type": "PAGE_DOWN", "value": "PRESS", "properties": [("name", "MACHIN3_MT_views_pie")]}],
        "ALIGN_PIE": [{"keymap": "Mesh", "idname": "wm.call_menu_pie", "type": "A", "value": "PRESS", "alt": True, "properties": [("name", "MACHIN3_MT_align_pie")]}],
        "WORKSPACE_PIE": [{"keymap": "Window", "idname": "wm.call_menu_pie", "type": "PAUSE", "value": "PRESS", "properties": [("name", "MACHIN3_MT_workspace_pie")]}],
        }
